"""Pydantic models for the policy quick-help integration."""

from typing import List, Literal, Optional

from pydantic import BaseModel, Field


class CopilotHelpRequest(BaseModel):
    question: str = Field(..., min_length=1, description="The policy question to ask")
    context: Optional[str] = None  # optional policy or operational context
    department: Optional[str] = None
    provider: Optional[Literal["google_gemma", "azure_openai", "ollama", "vllm"]] = Field(
        None,
        description=(
            "Request-level LLM provider override "
            "('google_gemma' | 'azure_openai' | 'ollama' | 'vllm')"
        ),
    )
    images: Optional[List[str]] = Field(
        None, description="List of Base64 encoded images for multimodal analysis (radiology, forms, etc.)"
    )


class CopilotSource(BaseModel):
    title: str
    url: Optional[str] = None
    provider: str = "Google Gemma 4"


class CopilotHelpResponse(BaseModel):
    answer: str
    sources: List[CopilotSource] = []
    confidence: str = "medium"  # "high" | "medium" | "low"
    disclaimer: str = (
        "This information is generated by the configured policy reference model for review only. "
        "Always verify against current institutional policy and do not treat it as legal, "
        "clinical, or compliance certification."
    )
    response_type: str = "policy_reference"
