apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cliniq.fullname" . }}-secret
  labels:
    {{- include "cliniq.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"  # Ideally replace this with Azure Key Vault CSI Provider backing in enterprise
type: Opaque
stringData:
  OPENAI_API_KEY: "change-me-in-production-or-use-csi"
  SECRET_KEY: "change-me-in-production-or-use-csi"
